var tank_Nevek = [];
tank_Nevek["1"] = "Az M3 könnyűharckocsi (angolul Light Tank M3) az Amerikai Hadsereg megrendelésére kifejlesztett könnyűharckocsi volt, amelyet a második világháborúban alkalmaztak.  Elődje a T2E1 fejlesztési nevű M2 (könnyűharckocsi) volt, amelyet 1935-ben kezdtek tervezni. A módosított M2-t 1941 márciusában kezdték gyártani M3 jelzéssel. A korabeli könnyűharckocsiktól jelentősen el nem térő járművet a harctéri tapasztalatok alapján modernizálták, és ezt a változatot M5 könnyűharckocsi néven rendszeresítették. Az M3 névadójául az amerikai polgárháború egyik tábornoka, James Ewell Brown Stuart szolgált. Ez a Stuart név a teljes családot jellemezte később. A britek Honey-nak becézték (magyarul „Édes”, „Kedves”, vagy „Drága” a nők után). Konkurensei a német Panzerkampfwagen I és Panzerkampfwagen II, a szovjet T–26, –27, –40, –50, –60, –70, a lengyel 7TP valamint a japán Type 95 Ha-Go és Type 97 Chi-Ha. A típust bevetették a világháború összes hadszínterén.";
tank_Nevek["2"] = "A Mark I-es nehézharckocsi, a világ első igazi harckocsija volt. A brit hadsereg fejlesztette ki az első világháború állóháborújának áttörésére. A Mark I a Centipide (Százlábú), vagy egy ideig Big Willie néven, majd véglegesen Mother (Anya) néven ismert prototípusból kifejlesztett harckocsi, amelyet a Holt traktor alvázára terveztek.A Mark IV-es volt az első jelentős szerkezeti módosítás. A Mark I-es átalakított változata volt, erősebb páncélzattal látták el, ami megnövelte a személyzet túlélőképességét. Az öntöttvas motorblokkot felváltotta az alumínium, a hűtőrendszert javították. Az erkélyek felfüggesztésén is változtattak, melyeket aztán könnyebb volt fel- és leszerelni a vasúti szállításhoz. A harckocsiágyút ugyanolyan űrméretű, de rövidebb lövegre cserélték, ami súlymegtakarítást eredményezett.A harckocsigyártó részleg (Tank Supply Department) vezetője, Albert Gerald Stern új meghajtást és erőátviteli rendszert tervezett a harckocsinak. Azonban a tervezési munkák következtében a gyártást nem sikerült időben elkezdeni, és előállítani a megszabott 200 darabszámot az 1917. április 1-jén induló offenzívához. A Mark IV Male négy Lewis géppuskát és két QF 6 pounder Hotchkiss ágyút hordozott, a Female változat pedig hat géppuskát.Összesen 1220 darab készült: 420 ágyúval és géppuskákkal ellátott Male, 595 géppuskákkal felszerelt Female és 205 műszaki harcjármű.";
tank_Nevek["3"] = "A Panzerkampfwagen III (Panzer III vagy Sd. Kfz 141) német közepes harckocsi, melynek gyártását 1937-ben kezdték meg. 1940-től egészen 1943 közepéig a német harckocsiegységek gerincét képezte, ezáltal a második világháború egyik legmeghatározóbb páncélos típusává vált. Első vonalbeli harcjárműként egészen 1943 végéig használták, de az alapkonstrukció ezt követően sem veszett ki nyomtalanul a német páncélos egységek kötelékéből. Parancsnoki, rohamlöveg, tüzérségi önjáró, támogató és egyéb speciális célokra átalakított változatai végigszolgálták a második világháborút.";
tank_Nevek["4"] = "A Panzerkampfwagen V Panther (jelentése párduc) a Harmadik Birodalom egy közepesharckocsi-típusa, melyet a második világháború alatt fejlesztettek ki és alkalmaztak. Német katonai jelölése Sd.Kfz. 171. A PzKpfw V Panther a Szovjetunió-beli nagy német páncélos veszteségeket volt hivatott csökkenteni, ugyanis a szovjetek korszerű T–34-ei megtizedelték az 1941-ben a keleti fronton szolgálatot teljesítő német harckocsikat (PzKpfw III és IV-eseket).A Panther besorolása tömeg szerint: a Panther megnevezése bizonytalanságot kelt, a németek esetenként közepesnek, máshol nehéznek minősítették a Panther harckocsit. A tömege alapján azonban (44 800 kg) ugyanúgy a nyugati szövetségesek, mint a szovjetek értelmezése szerint a nehézharckocsik közé tartozott (az amerikai Pershingek és a szovjet ISZ-típusú harckocsik voltak hasonló tömegkategóriában). A Panther tömeg szerinti besorolása egy egyszerű módszerrel eldönthető, aminek lényege a közepes és a nehéz harckocsik tömegadatainak összevetése a Panther tömegével. Ennek alapján a Panther egyértelműen a nehézharckocsi kategóriába sorolandó.[2]1941. november 18-án egy különleges bizottság érkezett a Szovjetunióban harcoló 2. Páncélos hadtesthez, hogy felmérjék a helyzetet, és felállítsák azokat a követelményeket, amelyek szerint fejlesztik ki az új harckocsit. Ennek keretében beszéltek a német páncélostisztekkel, és megtekintettek pár zsákmányolt T–34-est. A csoport tagjai, Porsche professzor, Oswald (az MAN mérnöke) és dr. Aders (Henschel). A fejlesztéssel párhuzamosan foglalkozott a Daimler Benz és a MAN. A Daimler-Benz prototípusa, a VK3002 külsőleg szinte a T–34-es pontos mása volt, és ez a fronton problémákhoz vezetett volna, ezért a gyár megszakította a projektet. A MAN prototípusa sokkal ígéretesebbnek mutatkozott, nagyobb volt a hatótávolsága, mint a Daimler-Benz változatnak, és benzin-üzemű motorral volt felszerelve. A MAN két darabot gyártott le (VK 3002 (M) és VK 3003 (M)), és mindkettőt tesztelték az Eisenach melletti gyakorlópályán. A sikeres tesztek után elindították a gyártást, a harckocsikat a MAN, a Daimler-Benz, a Henschel und Sohns AG és a Maschinenfabrik Niedersachsen Hannover (MNH) nehézgépgyárakban készítették – egy harckocsi gyártási költsége 117 000 birodalmi márka volt.";
tank_Nevek["5"] = "A T–34 („три́дцатьчетвёрка”) szovjet közepes harckocsi, melyet elsősorban a második világháború idején, 1941 és 1945 között vetettek be. A második világháború egyik legsikeresebb harckocsitípusának mondható. Elismertségéhez hozzájárult több eredeti, előnyös műszaki megoldása is. A harckocsi már a háború közben, de főleg utána legendává vált, ami nagyban megnehezíti az objektív, ideológiamentes megítélését.";
tank_Nevek["6"] = "A Panzerkampfwagen VI, más néven Tiger (magyarul Tigris)[j 1] harckocsi minden tekintetben a második világháborús német haditechnika-fejlesztési erőfeszítések mintapéldája. A típust először 1942 augusztusában vetették be Leningrádhoz közel, a Ladoga-tó térségében.Később szinte az összes hadszíntéren megjelent: a keleti fronton, Észak-Afrikában, Olaszországban, Normandiában, harcolt az Ardennekben és Magyarországon is a Harmadik Birodalom 1945-ös kapitulációjáig. Védettségének és tűzerejének köszönhetően neve egybeforrt a legyőzhetetlenséggel. A szövetségesek főképp nagy teljesítményű, 8,8 cm-es lövege és vastag páncélzata miatt tartottak tőle. A szövetségesek elsődlegesen leküzdendő harckocsijává lépett elő, a jármű gyenge pontjait azonban hamar kitapasztalták. A háború végére harctéri fölénye egyre csökkent, mivel a szövetségesek egyre hatékonyabb páncéltörő ágyúkat állítottak hadrendbe, valamint a legtöbbet a levegőből küzdötték le. 1945 elején már csak igen kis példányszámban volt szolgálatban, de még Berlin utcáin is harcolt az utolsó napokban. A Tigris megjelenése óriási technikai versenyhez vezetett, mivel a szövetségesek nem rendelkeztek olyan eszközökkel, amelyek a német nehézpáncélos leküzdéséhez alkalmasak lettek volna. Az amerikaiak az M4 Sherman harckocsit 1940-ben kezdték fejleszteni, 1942-ben állították rendszerbe, és a Tigris rögtön elavulttá tette. Ugyanígy jártak az angolok és a szovjetek valamennyi típusukkal. Megindult az erős páncélozottság és a nagy tűzerő utáni hajsza. A Shermant és a T–34-est egyre erősebb lövegekkel látták el. Kifejlesztették a Sherman Fireflyt kifejezetten a Tigris (később a Párduc) ellen, a szovjetek pedig a teljes löveges harcjármű-állományukat áttervezték és átalakították.";


function szamKiiras(elem, index) {
    var ujElem = document.createElement("option");
    var ujSzoveg = document.createTextNode(index);
    ujElem.appendChild(ujSzoveg);
    document.getElementById("kSzam").appendChild(ujElem);
}

function tank_Kiiras(tank) {
    document.getElementById("veg").innerHTML = tank_Nevek[tank];
}